version: "3.1"
services:
  pd_ui:
    build:
      context: ../pusoy-dos-ui
    volumes:
      - ../pusoy-dos-ui:/app
    ports:
      - 8080:8080
    environment:
      VIRTUAL_HOST: soydos.test
  pd_server:
    build:
      context: ../pd-server
    ports:
      - 8081:8080
    environment:
      VIRTUAL_HOST: api.soydos.test
      UI_HOST: https://soydos.test
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pusoydos
      POSTGRES_USER: pd
      POSTGRES_DB: pusoydos


  flyway:
    image: boxfuse/flyway:5.2.4
    command: migrate
    volumes:
      - ../pd-db/sql:/flyway/sql
    depends_on:
      - postgres
    environment:
      FLYWAY_USER: pd
      FLYWAY_PASSWORD: pusoydos
      FLYWAY_URL: "jdbc:postgresql://postgres:5432/pusoydos"



  loadbalancer:
    ports:
      - 80:80
      - 443:443
    tty: true
    image: jwilder/nginx-proxy
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

