version: "3.1"
services:
  pd_ui:
    build:
      context: ../pusoy-dos-ui
    volumes:
      - ../pusoy-dos-ui:/app
    ports:
      - 8080:8080
    environment:
      VIRTUAL_HOST: soydos.test
  pd_server:
    build:
      context: ../pd-server
    ports:
      - 8081:8080
    environment:
      VIRTUAL_HOST: api.soydos.test

  loadbalancer:
    ports:
      - 80:80
      - 443:443
    tty: true
    image: jwilder/nginx-proxy
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

